### PR TITLE
Enable withCredentials for XHR when userId cookie exists

### PR DESCRIPTION
**Pull request by vancehuang**
- This should only apply to fetching segments (which should hopefully
  be equivalent to the original customization in dash.js).
- withCredentials for XHR is set to false by default.
- Do we need to make it further configurable from UniPlayer SDK somehow?

### CODE REVIEW

**Comment by vancehuang** [comment]
Hi @havber, @torerikal, @thomaslund,
Does this change look ok? Not sure if we need to make a new setting in app/config.js -> UniPlayer shakaVideoAdapters.js -> shaka-player to control this.

**Comment by torerikal** [comment]
Here are two considerations for your question about making it configurable:
1. The userId cookie (unknown to me), might be HttpOnly, and not visible to Javascript. Note that it would still be visible through XHRs with credentials, provided Domain etc. is correct set up.
2. Turning on withCredentials when not intended, would often give CORS issues, if I remember correctly.

So, yes, it should definitely be controlled via configuration: Applied with the configure() method in shaka.player.Player, and turned off by default.

**Comment by vancehuang** [comment]
Thanks for comment. Will make it further configurable. FYI. userId cookie is based on the original patch in dash.js below.

**Comment by torerikal** [comment]
Alright. I think it is safer to cover the possibility of HttpOnly being applied to the cookie.

**Comment by torerikal** [comment]
Looks better, but just a final question: Is it required to test that the cookie is present? @havber

Again, this could be a problem if the cookie inadvertently becomes invisible, after someone decides marking it as HttpOnly due to security advices. 

I am stressing the HttpOnly thing, because of bad experiences with fragile solutions relying on HttpOnly not being enforced.

**Comment by havber** [comment]
@vancehuang LGTM. You could probably update the example config to reflect that the cookie checking logic no longer is valid. Otherwise 👍

**Pull request merged**
